MSG_LEVEL_NONE = 0
MSG_LEVEL_FATAL = 1
MSG_LEVEL_WARN = 2
MSG_LEVEL_NOTICE = 3
MSG_LEVEL_INFO = 4
MSG_LEVEL_DEBUG = 5

CP_OPTION_BORDER_MODE_U = 1
CP_OPTION_BORDER_MODE_V = 2
CP_OPTION_CURV_MODE = 3
CP_OPTION_BORDER_OFFSET_U = 5
CP_OPTION_BORDER_OFFSET_V = 6
CP_OPTION_SMOOTH_U_BEGIN = 7
CP_OPTION_SMOOTH_U_END = 8
CP_OPTION_REF_LINE_SEARCH_U = 9
CP_OPTION_REF_LINE_SEARCH_U_FRAC = 10
CP_OPTION_REF_LINE_CLOSE = 11
CP_OPTION_REF_LINE_FAR = 12
CP_OPTION_REF_LINE_CONTINUE = 13
CP_OPTION_WARN_MSGS = 14
CP_OPTION_CHECK_EPS = 15
CP_OPTION_CHECK_INC = 16
CP_OPTION_CHECK_TOL = 17
CP_OPTION_WARN_CURV_LOCAL = 18
CP_OPTION_WARN_CURV_GLOBAL = 19

BORDER_MODE_NONE = 0
BORDER_MODE_EX_ZERO = 1
BORDER_MODE_EX_KEEP = 2
BORDER_MODE_REPEAT = 3
BORDER_MODE_REFLECT = 4

REF_LINE_EXTRAPOLATE = 0
REF_LINE_CLOSE_TRACK = 1

CURV_LATERAL = 0
CURV_REF_LINE = 1

MOD_SCALE_Z = 21
MOD_SCALE_SLOPE = 22
MOD_SCALE_BANK = 23
MOD_SCALE_LENGTH = 24
MOD_SCALE_WIDTH = 25
MOD_SCALE_CURVATURE = 26
MOD_GRID_NAN_MODE = 27
MOD_GRID_NAN_OFFSET = 28
MOD_REF_POINT_V = 29
MOD_REF_POINT_V_FRAC = 30
MOD_REF_POINT_V_OFFSET = 31
MOD_REF_POINT_U = 32
MOD_REF_POINT_U_FRAC = 33
MOD_REF_POINT_U_OFFSET = 34
MOD_REF_POINT_X = 35
MOD_REF_POINT_Y = 36
MOD_REF_POINT_Z = 37
MOD_REF_POINT_PHI = 38
MOD_REF_LINE_OFFSET_X = 39
MOD_REF_LINE_OFFSET_Y = 40
MOD_REF_LINE_OFFSET_Z = 41
MOD_REF_LINE_OFFSET_PHI = 42
MOD_REF_LINE_ROT_CENTER_X = 43
MOD_REF_LINE_ROT_CENTER_Y = 44

GRID_NAN_KEEP = 0
GRID_NAN_SET_ZERO = 1
GRID_NAN_KEEP_LAST = 2

ORIENT_FWD = 0
ORIENT_REV = 1
